version: '3'
services:
  redis:
    image: redis:3
  sensu:
    build: ./sensu
    volumes:
      - ./server/conf.d:/etc/sensu/conf.d
      - ./server/handlers.d:/etc/sensu/handlers.d
    command: sensu-server -d /etc/sensu
  client:
    build: ./sensu
    volumes:
      - ./client/conf.d:/etc/sensu/conf.d
      - ./client/check.d:/etc/sensu/check.d
    command: sensu-client -d /etc/sensu
  api:
    build: ./sensu
    volumes:
      - ./api/conf.d:/etc/sensu/conf.d
    ports:
      - 4567:4567
    command: sensu-api -d /etc/sensu
  dashboard:
    image: uchiwa/uchiwa
    volumes:
      - ./uchiwa:/config
    ports:
      - 3001:3000






